import { createApp } from "vue";
import "./style.css";
import ElementPlus from "element-plus";
import { createPinia } from "pinia";
import "element-plus/dist/index.css";
import axios from "axios";
import App from "./App.vue";
axios.defaults.baseURL = "http://118.178.132.49:8089/jydam";
const app = createApp(App);
const pinia = createPinia();
app.config.globalProperties.$http = axios;
app.use(ElementPlus).use(pinia).mount("#app");
